version: '3.8'

services:
  weatherapi:
    hostname: weatherapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"