name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  OWNER: ${{ github.repository }}
  IMAGE_NAME: weatherapi
  ACA_RG: rg-aca-dev-env
  AZ_LOCATION: australiaeast

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
      - name: Generate Unique Id
        id: uuid-create
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
      - name: Create Container Apps Environment
        id: aca-env-create
        uses: azure/CLI@v1
        with: 
         azcliversion: 2.40.0
         inlinescript: |
            az extension add --name containerapp --upgrade
            az provider register --namespace Microsoft.App
            az provider register --namespace Microsoft.OperationalInsights
            az containerapp env create --name ${{ github.actor }}-${{ steps.uuid-create.outputs.uuid }} --resource-group ${{ env.ACA_RG }} --location ${{ env.AZ_LOCATION }}

      - name: Deploy to Container Apps Environment
        id: aca-deploy
        uses: azure/CLI@v1
        with:
          azcliversion: 2.40.0
          inlinescript: |
            az extension add --name containerapp --upgrade
            az extension add --name containerapp-compose --upgrade
            az provider register --namespace Microsoft.App
            az provider register --namespace Microsoft.OperationalInsights
            az containerapp compose create --environment ${{ github.actor }}-${{ steps.uuid-create.outputs.uuid }} --resource-group ${{ env.ACA_RG }} --compose-file-path ./docker-compose.yml --location ${{ env.AZ_LOCATION }}